stages:
  - build
  - test
  - packaging
  - docker-images

variables:
  MAVEN_CLI_OPTS: "-s ci_settings.xml --batch-mode --errors --fail-at-end"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  image: maven:3.9.7
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

tests:
  stage: test
  image: maven:3.9.7
  needs:
    - build
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

packaging:
  stage: packaging
  image: maven:3.9.7
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - build
    - tests
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests -Dexecutable.enabled=false -Dlayered.enabled=true package
  artifacts:
    paths:
      - target/demo-server-*.jar
    expire_in: 1 hour

include:
  - /.gitlab-ci/docker-build.yml

