{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "demo-server.labels" . | nindent 4 }}
    release: prometheus
  name: {{ include "demo-server.name" . }}
spec:
  groups:
  - name: application-rules
    rules:
{{ toYaml .Values.metrics.prometheusRule.rules | indent 6}}
{{- end }}
