{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "demo-server.labels" . | nindent 4 }}
    release: prometheus
  name: {{ include "demo-server.name" . }}
spec:
  endpoints:
    - port: http
      path: '/actuator/prometheus'
      scheme: http
      interval: 10s
      honorLabels: true
  jobLabel: demo
  selector:
    matchLabels:
      {{- include "demo-server.selectorLabels" . | nindent 8 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
