docker-image:
  stage: docker-images
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  needs:
    - packaging
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin
  after_script:
    - docker logout
  script:
    - docker build -t $CI_REGISTRY_IMAGE/demo-server:$CI_COMMIT_TAG --build-arg JAR_FILE=./target/demo-server-*.jar .
    - docker push $CI_REGISTRY_IMAGE/demo-server:$CI_COMMIT_TAG

helm-package:
  stage: docker-images
  image:
    name: alpine/helm:3.5.3
    entrypoint: [""]
  variables:
    REPO_NAME: demo-server
    CHART_PATH: helm
    CHART_NAME: demo-server
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
  before_script:
    - apk add git
    - helm plugin install --version=v0.9.0 https://github.com/chartmuseum/helm-push.git
    - >
      helm repo add ${REPO_NAME}
      --username ${CI_REGISTRY_USER}
      --password ${CI_REGISTRY_PASSWORD}
      ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - env
    - helm dependency build ${CHART_PATH}
    - helm lint ${CHART_PATH}
    - helm package --version ${CI_COMMIT_TAG} --app-version ${CI_COMMIT_TAG}  ${CHART_PATH}
    - helm push ${CHART_NAME}*.tgz ${REPO_NAME}
